### ISSUE TITLE
GeoID miss when joining with census blocks?

### ISSUE THREAD

**Issue by stuartlynn** [enigma-io/smoke-alarm-risk#3]
Trying to map the results of the analysis here by joining the smoke

It looks like perhaps there is a miss match between the GeoID's in the smoke risk scores and the census blocks which is specific to certain states. 

https://team.cartodb.com/u/stuartlynn/viz/7ba9f95e-5b04-11e5-8fc5-0e0c41326911/map

**Comment by abelsonlive** [comment]
Thanks for reaching out! What census shapefile are you using?

**Comment by stuartlynn** [comment]
Its the tl_2014_block_groups dataset in CartoDB. 

I think I have figured it out though. It looks like the block groups in that file are padded so 11170306092 in the smoke-alarm-risk data should be 011170306092 in the census data. Should be able to resolve here now. 

Thanks for the quick reply.

**Comment by stuartlynn** [comment]
That seems to have fixed it 

http://cdb.io/1iqB82a
